<?php

namespace Admin\AdminBundle\Entity;

/**
 * DirectorioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DirectorioRepository extends \Doctrine\ORM\EntityRepository
{
}
