<?php

namespace Admin\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * seguimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgenciaHojadevidaRepository extends EntityRepository
{
 public function notificarfind($idAgencia){
      $result = $this->createQueryBuilder('n')
              ->andWhere('n.Estado =:Estado')->setParameter('Estado','Inactivo')
              ->andWhere('n.Activo =:activo')->setParameter('activo',true)
              ->andWhere('n.idAgencia =:agencia')->setParameter('agencia',$idAgencia)
                ->getQuery()
                ;
      return $result->getArrayResult();
 }
 /// agencias que pertenecen a un book en especifico $id es id hojadevida
 public function agenciasbook($idHojadevida){
     $result = $this->createQueryBuilder('ah')
         ->join('ah.idHojadevida','h')
         ->join('ah.idAgencia','a')
         ->andWhere('a.privado =0')
         ->andWhere('ah.Activo =1')
         ->andWhere('ah.Estado =:Estado')
         ->andWhere('h.id =:id')
         ->setParameter('id',$idHojadevida)
         ->setParameter('Estado','Activo')
         ->getQuery();
     return $result->getResult();
 }
    public function idsHojasdevida($idAgencia){
     //retorna ids de hojas de vida segun id de agencia
        //retorna array
        $ids = $this->createQueryBuilder('ah')
            ->select('h.id')
            ->join('ah.idHojadevida','h')
            ->join('ah.idAgencia','a')
            ->andWhere('a.id =:idAgencia')->setParameter('idAgencia',$idAgencia)
            ->getQuery();
        return $ids->getArrayResult();
 }
}
