<?php

namespace Admin\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * HojadevidaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HojadevidaRepository extends EntityRepository
{
    public function countAgenciaHojadevida($idAgencia){
        //Cuenta las hojas de vida que no pertenecen a la agencia
        //retorna entero
        $em = $this->getEntityManager();
        $ids=$em->getRepository('AdminAdminBundle:AgenciaHojadevida')->idsHojasdevida($idAgencia);
        $idsHojasdevida = $this->createQueryBuilder('h')
            ->select('h.id')
            ->getQuery()->getArrayResult();
        $HojasdevidaAgencias=array();
        foreach ($ids as $id){
            array_push($HojasdevidaAgencias,$id['id']);
        }
        $Hojasdevida=array();
        foreach ($idsHojasdevida as $idh){
            array_push($Hojasdevida,$idh['id']);
        }
        return count($Hojasdevida)-count($HojasdevidaAgencias);
    }
}
