<?php

namespace Admin\AdminBundle\Repository;

/**
 * seguimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeguimientoBookRepository extends \Doctrine\ORM\EntityRepository
{
    public function countHojadevida($idHojadevida){
        $query= $this->createQueryBuilder('h')
            ->select('COUNT(h.id)')
            ->where('h.idHojadevida=:id')
            ->setParameter('id',$idHojadevida)
            ->getQuery();
        if($query->getOneOrNullResult()){
            return intval($query->getOneOrNullResult()[1]);
        }
        else{
            return null;
        }
    }
}
