<?php

namespace Admin\AdminBundle\Repository;

/**
 * seguimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeguimientoAgenciaRepository extends \Doctrine\ORM\EntityRepository
{
    
}
