<?php

namespace Admin\AdminBundle\Repository;

/**
 * SuscripcionusuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuscripcionusuarioRepository extends \Doctrine\ORM\EntityRepository
{
}
