<?php

namespace Admin\AgenciaBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * SolicitudRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SolicitudRepository extends EntityRepository
{
    public function countAll(){
     $count=$this->createQueryBuilder('s')
         ->select('COUNT(s.id)')
         ->where('s.activo =1')
         ->andWhere('s.privado =0')
         ->getQuery()->getOneOrNullResult()[1]
     ;
     return $count;
    }
}
